#!/bin/bash

## For Keybinds
sxhkd &

## Setup monitors and workspace
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

## Colors
bspc config normal_border_color     "#0F1C1E"
bspc config active_border_color     "#587B7B"
bspc config focused_border_color    "#587B7B"
bspc presel_feedback_color          "#1D3337"

## Basic behaviour
bspc config border_width            1
bspc config window_gap              30

bspc config split_ratio             0.50
bspc config borderless_monocle      false
bspc config gapless_monocle         false

bspc config focus_follows_pointer   true

## Rules
bspc rule -a *:FloatTerm state=floating
bspc rule -a spotify desktop=4

## Autostarts
xsetroot -cursor_name left_ptr
feh --bg-scale ~/Bilder/Wallpaper/tauben_terafox.jpg
~/.config/polybar/launch.sh
~/.config/picom/start.sh
xss-lock xsecurelock &
xset s on
xset s 600
